# Generated by Django 3.2 on 2021-05-18 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210518_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.ImageField(default='profile2.png', upload_to='customers_images'),
        ),
    ]
