# Generated by Django 3.2 on 2021-05-22 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_contactus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name_plural': 'contact us'},
        ),
    ]
