# Generated by Django 3.2 on 2021-05-22 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20210522_2158'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactUs',
        ),
    ]
