# Generated by Django 3.2 on 2021-05-23 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_contactus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
