# Generated by Django 3.2 on 2021-05-31 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='emails',
            field=models.BooleanField(default=True),
        ),
    ]
