# Generated by Django 3.2 on 2021-05-31 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_customer_emails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='emails',
            new_name='promo_emails',
        ),
    ]
