# Generated by Django 3.2.3 on 2021-06-09 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_image',
            field=models.ImageField(default='', upload_to='payment_scrnsht'),
        ),
    ]
